apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    enabled: true
    samplingRate: "1"
    expandParams: true
    includeBody: true
    zipkin:
      #endpointAddress: http://localhost:9411/api/v2/spans
      endpointAddress: http://host.docker.internal:19411/api/v2/spans
