version: '3.4'
networks:
  dapr: null

services:
  myfrontend:
    image: ${DOCKER_REGISTRY-}myfrontend
    build:
      context: .
      dockerfile: MyFrontEnd/Dockerfile
    ports:
      - "51000:50001"
    networks:
      - dapr
    depends_on:
    - dapr-placement

  myfrontend-dapr:
    container_name: myfrontend-sidecar
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "--app-id", "MyFrontEnd",
      "--app-port", "80",
      "--placement-host-address", "dapr-placement:50006", # Dapr's placement service can be reached via the docker DNS entry
      "--components-path", "/components",
      "--config", "/config/config.yaml"
    ]
    depends_on:
      - myfrontend
    network_mode: "service:myfrontend"
    volumes:
    - "./dapr/components:/components"
    - "./dapr/config.yaml:/config/config.yaml"

  mybackend:
    image: ${DOCKER_REGISTRY-}mybackend
    build:
      context: .
      dockerfile: MyBackEnd/Dockerfile
    ports:
      - "52000:50001"
    networks:
      - dapr
    depends_on:
    - dapr-placement

  mybackend-dapr:
    container_name: mybackend-sidecar
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "--app-id", "MyBackEnd",
      "--app-port", "80",
      "--placement-host-address", "dapr-placement:50006", # Dapr's placement service can be reached via the docker DNS entry
      "--components-path", "/components",
      "--config", "/config/config.yaml"
    ]
    depends_on:
      - mybackend
    network_mode: "service:mybackend"
    volumes:
    - "./dapr/components:/components"
    - "./dapr/config.yaml:/config/config.yaml"

  dtc-maildev:
    container_name: dtc-maildev
    image: maildev/maildev:latest
    environment:
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_WEB_PORT=80
    ports:
      - "4000:80"   # allows us to access the web console

  dtc-zipkin:
    container_name: dtc-zipkin
    image: openzipkin/zipkin-slim
    ports:
      - "19411:9411"  # allows us to access the web console

  dapr-placement:
    container_name: dapr-placement
    image: "daprio/dapr"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
    - '9092:9092'
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=broker,controller
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    - KAFKA_CFG_BROKER_ID=1
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
    - ALLOW_PLAINTEXT_LISTENER=yes