apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messages
spec:
  type: bindings.kafka
  version: v1
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: localhost:9092
  # consumer configuration: topic and consumer group
  - name: topics
    value: messages
  - name: consumerGroup
    value: $Default
  # publisher configuration: topic
  - name: publishTopic
    value: messages
  - name: authRequired
    value: "false"