version: '3.8'

services:
  myfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mybackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  publishbackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro